### ISSUE TITLE
Channel shifting

### ISSUE THREAD

**Issue by Devilscave** [RobTillaart/TLC5947#2]
Hello Rob,
I have noticed a problem with the channel assignment.
I use your library to control 24 LEDs separately, sometimes together or in various blink algorithms. Now I have noticed. When I define the channels, it always starts to mix in another one slightly from 6 onwards. So from 6 the 7 is already lit, at 8 clearly the 9, from 12 the 13 and at 22 even channel 23 & 24.
I have written a small example to show you the error. 
The channels are switched on one after the other and switched off again after the cycle, in the serial monitor you can see when which channel is written with which value. Unfortunately it does not match reality. At 21 I have 2-3 more LEDs on.

```cpp
#include "TLC5947.h"
TLC5947 tlc(12, 11, 10,9);      //<--- attencion
int i, an = 4095;

void setup(){
  Serial.begin(9600);
  tlc.begin();
}

void loop(){
  for ( i = 0; i < 24; i++)
  {
    tlc.setPWM(i, an);
    delay(500);
    tlc.write();
    Serial.print(i);
    Serial.print(" = ");
    Serial.println(an);
    if(i == 23){ an = an ?0:4095;}
  }
}
```

**Comment by RobTillaart** [comment]
Thanks for reporting, 
I will investigate asap

**Comment by RobTillaart** [comment]
Q: What board do you use?


Hypothesis 0
Wiring problem

Q: do you have pull ups on the data and clock line?
If so what value?

Hypothesis 1
The clocking of bits - in write() function - might be too fast.

Hypothesis 2
The number of bits sent is too large.

**Comment by RobTillaart** [comment]
hypotheses 2 is most likely.

Can you change in the .cpp file
In the write function
```mask = 0x1000```
Into 
```mask = 0x0800```

Two times.
In the AVR optimized part
And in the "normal" part

**Comment by RobTillaart** [comment]
No hardware to test with so I added a counter to count the nr of bits send in **write()**.
It did send 13 bits instead of 12.

That means the hypothesis 2 is confirmed.
A new version 0.2.0 will be build asap

I also want to add an RGB interface to control 8 RGB LEDS, so might take some time.

**Comment by Devilscave** [comment]
Hello, thanks for the quick reply.
Nice that you found it right away. I will be happy to test it.
Instead of implementing RGB, I think "daisy chaining" would be more important. Adafruit already offers enough RGB. Your library is characterized by the fact that the channels can be addressed individually.

**Comment by RobTillaart** [comment]
I still need to buy extra hardware to test the daisy chaining, it is on my (long) TODO list.

Develop branch is expected within 15 minutes.

**Comment by RobTillaart** [comment]
Develop branch and PR created, build is running.

**Comment by Devilscave** [comment]
I changed the .cpp and immediately did a hardware test. Now they are controlled correctly and no longer scatter. Thanks for that.
I still have a few tests to do with this lib and will be happy to report any further problems. If you want to have something tested, I am also happy to help.

**Comment by Devilscave** [comment]
> F: Welches Board verwenden Sie?

LGT8F328P_Nano

**Comment by RobTillaart** [comment]
If you could verify the develop branch would be great!

**Comment by RobTillaart** [comment]
Daisy chaining is mostly 
- make a configurable max channels 
- allocate a large enough array to hold all PWM values.
  - it might be useful to compact 4 x 12 bits in 3 x uint16_t to save some RAM. (optimization).


will create a test branch today.

**Comment by RobTillaart** [comment]
Created a **daisy_chain** branch in which the constructor has an extra parameter uint8_t deviceCount.
This may be 1..10 or so as the internal variable _channels is also an uint8_t.

If you want, you can give it a try - I have to attend other tasks 

![image](https://github.com/RobTillaart/TLC5947/assets/462844/c2dca571-1205-4910-bfc6-e672f04febdc)

**Comment by RobTillaart** [comment]
Daisy chain branch is updated after some (dry) test runs with the performance sketch.

An Arduino UNO did work with performance sketch and 30 devices, and failed at 35 devices. 
30 devices == 720 channels is using 1440 bytes so memory
performance scales linear with number of devices.

ESP32 - test run 200 devices still worked.
```
Channels: 4800
SETPWM	884
SETRGB	462
WRITE	24112  (24 milliseconds)
```

So it looks like the daisy chain is reasonable prepared for a 0.3.0 version of the library.

**Comment by Devilscave** [comment]
Wow that's amazing, I was only thinking of 4-5 devices, so 96-120 channels. I'll have a look and give it a try. I'll report back.

**Comment by Devilscave** [comment]
> Wenn Sie den Entwicklungszweig überprüfen könnten, wäre das großartig!

Had a look at your RGB branch, wrote a little test example, actually I took the Adafruit_RGB example and adapted it to your LIB, works identically. See here:

```cpp
#include "TLC5947.h"

// How many boards do you have chained?
#define NUM_TLC5947 1

const int CLOCK = 12;
const int DATA  = 11;
const int LATCH = 10;
const int BLANK = 9;


TLC5947 tlc(CLOCK, DATA, LATCH, BLANK);


void setup() {
  Serial.begin(9600);
  
  Serial.println("TLC5947 test");
  tlc.begin();
  if (BLANK >= 0) {
    pinMode(BLANK, OUTPUT);
    digitalWrite(BLANK, LOW);
  }
}


void loop() {
  colorWipe(4095, 0, 0); // "Red" (depending on your LED wiring)
  delay(200);
  colorWipe(0, 4095, 0); // "Green" (depending on your LED wiring)
  delay(200);
  colorWipe(0, 0, 4095); // "Blue" (depending on your LED wiring)
  delay(200);
  rainbowCycle(10);
}

// Fill the dots one after the other with a color
void colorWipe(uint16_t r,  uint16_t g,  uint16_t b) {
  for(uint8_t i=0; i<8*NUM_TLC5947; i++) {
      tlc.setRGB(i, r, g, b);
      tlc.write();
      delay(200);
  }
}

// Slightly different, this makes the rainbow equally distributed throughout
void rainbowCycle(uint8_t wait) {
  uint32_t i, j;

  for(j=0; j<4096; j++) { // 1 cycle of all colors on wheel
    for(i=0; i< 8*NUM_TLC5947; i++) {
      Wheel(i, ((i * 4096 / (8*NUM_TLC5947)) + j) & 4095);
    }
    tlc.write();
    delay(wait);
  }
}

// Input a value 0 to 4095 to get a color value.
// The colours are a transition r - g - b - back to r.
void Wheel(uint8_t ledn, uint16_t WheelPos) {
  if(WheelPos < 1365) {
    tlc.setRGB(ledn, 3*WheelPos, 4095 - 3*WheelPos, 0);
  } else if(WheelPos < 2731) {
    WheelPos -= 1365;
    tlc.setRGB(ledn, 4095 - 3*WheelPos, 0, 3*WheelPos);
  } else {
    WheelPos -= 2731;
    tlc.setRGB(ledn, 0, 3*WheelPos, 4095 - 3*WheelPos);
  }
}
```

**Comment by RobTillaart** [comment]
Good to hear, for me green light to merge the develop branch into master and release 0.2.0

Then the daisy chaining version is next (at least for this repo)

**Comment by RobTillaart** [comment]
Issue is closed because of the merge, we can open a new one focused on the daisy chaining if needed.
My first actions are to get the build working again, meta data and documentation.
