### ISSUE TITLE
discuss Daisy Chaining

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/TLC5947#5]

**Comment by RobTillaart** [comment]
@Devilscave
Do you miss functions / functionality in the 0.3.0 daisy chain version?

Possible functions / functionality
- getDevices() returns nr set in the constructor
- allocation is done in the constructor and its success could be verified in **begin()**  TLC5947_CALLOC_ERROR  (should be in)
- compression of the internal buffer to reduce RAM usage (25% gain RAM, slightly slower)
- a derived class that uses 8 bits PWM - maps 0.255 unto 0..4095  (would save 50% RAM, at least interesting)
- shift the buffers (e.g. to move the pre-calculated buffer wave along the lights is faster than recalculate)
- ...

**Comment by Devilscave** [comment]
Sounds good, I'm testing it too but can't get it to work, I'm using it with a dynamic LED set but the 2 devise just seems to clone itself. It runs parallel to the first one. Could be my code though.

**Comment by RobTillaart** [comment]
You can post your code if you want a review.
Does your code work with one device? 
To have some reference to start from.

**Comment by Devilscave** [comment]
no this is a bigger project i am trying to create a demo that shows you my mistake. It may take some time because I have to narrow down the error first, anyway my device assignment my count quantity and the LED assignment is correct, but when selecting 40 LEDs both DEVICES work as cloned so they both show the same thing at the same time but only from 0-24 and not that the LED goes on until channel 40

**Comment by Devilscave** [comment]
I have tested it with the first demo from yesterday after a small adjustment to 48 channels, and this also runs cleanly, then the error must be with me, still looking.

**Comment by Devilscave** [comment]
OK I found it, if I start it with DEVICES = 1; it copies the devices and projects them onto the second one.
It only works if I set DEVICES = 2; from the beginning, a subsequent change is not actively applied. Probably tlc would have to be re-initialized with tlc.begin(); but this leads to a crash of the computer. I would only think of building a hardware based pre-setting or you make a dynamic change of the DEVICES possible.

**Comment by RobTillaart** [comment]
Dynamic means that devices parameter has to move from constructor to begin.
First free previous buffer and then allocate new buffer.

I will reread part of the datasheet, to see if I missed some signal

**Comment by Devilscave** [comment]
I think it was my mistake, I have now simply specified DEVICES with a fixed 4 as I only need a maximum of 96 channels anyway. I have thrown out the entire DEVICES assignment and simply control it via the LED count function, if less is specified, nothing is controlled. works for me.

**Comment by Devilscave** [comment]
Hello Rob,
I tested the Daisy_Chain yesterday and this morning, I came across a small "bug".
In principle it is not a bug, but it can lead to confusion.
If you specify only one board (DEVICES = 1), the control signals are duplicated on all other connected but not implemented boards, which creates a clone effect. As soon as you specify DEVICES = 2, the second board works in series with the first; if a third is connected, the signals from the first are cloned to the third. This should possibly be prevented as it can lead to unwanted effects.
Furthermore, I took the liberty of writing a new little demo for you which you can perhaps add to your project if you like.
Please let me know and have another look at it, you have all rights to customize it. 

```cpp
//
//      FILE: TLC5947_Daisy_Chain.ino
//    AUTHOR: Ricardo Franke
// PUBLISHER: Rob Tillaart
//   PURPOSE: Daisy_Chain_Demo
//       URL: https://github.com/RobTillaart/TLC5947


#include "TLC5947.h"

int DEVICES = 1;                          // set Amount of TLC5947 Boards

int led = 24*DEVICES;                     // this set Amount of LEDs per Board

int wait = 100;                           // set time between channel control
  

const int CLOCK = 13;
const int DATA  = 12;
const int LATCH = 11;
const int BLANK =  10;

TLC5947 tlc(DEVICES, CLOCK, DATA, LATCH, BLANK);

int i = 0;                                // zero bigthness
int a = 4095;                             // 100% bigthness

void setup(){
  
  Serial.begin(9600);                     // initial Serial Output
  tlc.begin();                            // initial TLC5947 library
}

void loop(){
  
  for ( i = 0; i < led; i++)
  {
    tlc.setPWM(i, a);
    delay(wait);
    tlc.write();
    Serial.print(i);
    Serial.print(" = ");
    Serial.println(a);
    if(i == led-1){ a = a ?0:4095;}
  }
}

//  -- END OF FILE --

```

(added syntax highlighting)

**Comment by Devilscave** [comment]
One more thing,
i have a little logic problem, maybe it's just in my head, but it gave me a lot of trouble at the beginning.
It's about the BLANK function. For me, the input logic is the wrong way round. 
When I write  ``tlc.dissable();`` the BLANK pin goes LOW and deactivates the switch-off, so the LEDs go on.
Shouldn't it then be ``TLC.enable();`` ? so just swap LOW and HIGH in the .cpp. is illogical for me. But it could be my head.
So when I write ``TLC.enable();`` the LEDs should not go ON for me. But I can also change this for myself in the .cpp.

**Comment by RobTillaart** [comment]
Thanks for your feedback.

As I have no hardware to test, the coming remarks is from my "head / datasheet interaction"

> If you specify only one board (DEVICES = 1), the control signals are duplicated on all other connected but not implemented boards, which creates a clone effect. As soon as you specify DEVICES = 2, the second board works in series with the first; if a third is connected, the signals from the first are cloned to the third. This should possibly be prevented as it can lead to unwanted effects.

The hardware clocks out what is put into it after 24 clock pulses, so if there is a device 2 it would get the bits from device 1.

You should be able to make this visible by adding a LED to the SOUT (?) line of device 1 and add a major **delay(200)**  in the **write()** function. All the bits should pass (24 x 12 = 288 pulses) which would take a minute or so.

----

Thanks for the example, I will include it

one comment is a bit odd

```cpp
int led = 24*DEVICES;                     // this set Amount of LEDs per Board
```

should this not be TOTAL amount of LEDS on all devices?
or does a board has multiple TLC devices?

**Comment by RobTillaart** [comment]
> One more thing,
i have a little logic problem, maybe it's just in my head, but it gave me a lot of trouble at the beginning.
It's about the BLANK function. For me, the input logic is the wrong way round.

I'll have to take a look at it, your interpretation sounds logical to me.

(back to some coding)

**Comment by RobTillaart** [comment]
FYI, added your example to the library - slightly modified

**Comment by RobTillaart** [comment]
From datasheet - about BLANK 

When BLANK is HIGH all is forced off, 
when BLANK is LOW the internal PWM is in control

So you are right, enable should set the line LOW,
also the constructor should default the line LOW.

Thanks for testing this 

![image](https://github.com/RobTillaart/TLC5947/assets/462844/cfaac131-cb3e-471b-ab8d-eb70b5dbd9d2)

**Comment by RobTillaart** [comment]
Patched BLANK polarity in **enable(), disable(), isEnabled()** and constructor

**Comment by RobTillaart** [comment]
Thinking about adding the old constructor for backwards compatibility.

Opinion?

```cpp
TLC5947::TLC5947(uint8_t clock, uint8_t data, uint8_t latch, uint8_t blank)
{
  TLC5947(1, clock, data, latch, blank);
}

TLC5947::TLC5947(int deviceCount, uint8_t clock, uint8_t data, uint8_t latch, uint8_t blank)
{
  if (deviceCount == 0) deviceCount = 1;
  _channels = deviceCount * 24;
  _clock    = clock;
  _data     = data;
  _latch    = latch;
  _blank    = blank;
  _buffer   = (uint16_t *) calloc(_channels, 2);
}

```

**Comment by Devilscave** [comment]
> Die Hardware taktet nach 24 Taktimpulsen aus, was in sie eingegeben wird. Wenn es also ein Gerät 2 gibt, würde es die Bits von Gerät 1 erhalten.
> 
> Sie sollten dies sichtbar machen können, indem Sie eine LED zur SOUT-Leitung (?) von Gerät 1 hinzufügen und eine größere **Verzögerung (200)** in der **write()-** Funktion hinzufügen. Alle Bits sollten passieren (24 x 12 = 288 Impulse), was etwa eine Minute dauern würde.

OK how do I explain it best...
I have checked the signal at SOUT, you are right, if ``DEVICES = 1`` then it passes the clock pulses to the next device, but if I set ``DEVICES = 2`` it does not do it, but only when the second device is to be addressed.
But isn't this a very counterproductive behavior?
Is it not possible to prevent or switch off the "clone output" with ``DEVICES = 1``?

**Comment by Devilscave** [comment]
> Thinking about adding the old constructor for backwards compatibility.
> 
> Opinion?
> 
> ```c++
> TLC5947::TLC5947(uint8_t clock, uint8_t data, uint8_t latch, uint8_t blank)
> {
>   TLC5947(1, clock, data, latch, blank);
> }
> 
> TLC5947::TLC5947(int deviceCount, uint8_t clock, uint8_t data, uint8_t latch, uint8_t blank)
> {
>   if (deviceCount == 0) deviceCount = 1;
>   _channels = deviceCount * 24;
>   _clock    = clock;
>   _data     = data;
>   _latch    = latch;
>   _blank    = blank;
>   _buffer   = (uint16_t *) calloc(_channels, 2);
> }
> ```

I think you can do that, but you don't necessarily have to. But you've actually already done it.

**Comment by RobTillaart** [comment]
![image](https://github.com/RobTillaart/TLC5947/assets/462844/a140e8b2-123f-4412-a2e2-426ca15556e7)

There is no line (signal) to switch off the SOUT in the schema above.
From the schema it looks like that the upper register is to be clocked out, independent of the number of devices.
It might be that the LATCH (XLAT) does something.

Note: If DEVICES == 2 and the first 24 leds are all 0 there will be no visible data on the SOUT as all bits are zero.

Will further explore the datasheet

**Comment by Devilscave** [comment]
No, I don't think you understand what I mean.
If I have 2 devices, it also works.
So why should a signal come out at SOUT when I specify a device and clone device 1 to device 2?
But if I specify ``DEVICES = 2``; Device 1 processes all LEDs first and then Device 2, so nothing is cloned there. 
Imagine I have a complete chain of TLC5947 boards, and I only want ``DEVICES = 1;``, then ALL the connected ones would display exactly the same at the same time. 
There must be a reason why the SOUT provides a signal in single operation. This should be prevented.

**Comment by Devilscave** [comment]
OK, the other way round, if I have connected 2 devices and activated them with ``DEVICES = 2;``, but only use 20 LEDs of the entire 48, why are only the first 20 of Device 1 used but not the first 20 of Device 2?
Because if I use ``DEVICES = 1;`` this is exactly what happens.

**Comment by Devilscave** [comment]
![devices](https://github.com/RobTillaart/TLC5947/assets/39168213/28cd861d-4082-4661-b16b-35de0ad1e836)
Pictures say more than 1000 words

**Comment by RobTillaart** [comment]
Here are some words,

_When the IC is powered on, the data in the grayscale data shift register and latch are not set to default values.
Therefore, grayscale data must be written to the GS latch before turning on the constant current output. BLANK
should be at a high level when powered on to keep the outputs off until valid grayscale data are written to the
latch. This avoids the LED being randomly illuminated immediately after power-up. If having the outputs turn on
at power-up is not a problem for the application, then BLANK does not need to be held high. The grayscale
functions can be controlled directly by grayscale data writing, even though BLANK is connected to GND._

So BLANK should be HIGH at start as that is safest option.

**Comment by RobTillaart** [comment]
> OK, the other way round, if I have connected 2 devices and activated them with DEVICES = 2;, but only use 20 LEDs of the entire 48, why are only the first 20 of Device 1 used but not the first 20 of Device 2?
Because if I use DEVICES = 1; this is exactly what happens.

That makes perfect sense to me.

When DEVICES == 1 and you have set 20 leds on, the GREYSCALE REGISTER of device 1 has pattern 11111111111111111110000 in it. When you call **write()** the library will clock in **24** new values, and the **existing 24** values from the register are shifted out (via SOUT) to the second device, which will display them on the pulse of XLAT.

When DEVICES == 2 and you have set 20 leds on the GREYSCALE REGISTER has pattern 11111111111111111110000 in it, AND
the greyscale register of device 2 has 0000000000000000000000 in it. When you call **write()** the library will clock in **48** new values **overwriting both** the GREYSCALE REGISTERS of device 1 and 2.

**Comment by RobTillaart** [comment]
Your question answers a question I had, what will happen if I do not clock all 24 bits.
From your experiment I may conclude that if I write only 12 values, the register will shift the led pattern 12 pins.
Problem would be that the actual LED pattern is out of sync with the internal buffer.

**Comment by RobTillaart** [comment]
FYI, 
updated the **enable()** polarity code in the branch
and some minor edits

**Comment by Devilscave** [comment]
> Your question answers a question I had, what will happen if I do not clock all 24 bits. From your experiment I may conclude that if I write only 12 values, the register will shift the led pattern 12 pins. Problem would be that the actual LED pattern is out of sync with the internal buffer.

I could not detect any shifting, the device works absolutely correctly with less than 24 channels, nothing is shifted.

**Comment by RobTillaart** [comment]
That is because **write()** will send 24 values and dont care if you are using 2 5 or 20 pins.

What I meant (in my mind) is that suppose you have a **wrtie(n)** that could send 0 .. 23 values it would. 
Such a function call would be twice as fast if you only shifted 12 values.
I will implement it so you can play with it an give your opinion on its value.
15 minutes

**Comment by RobTillaart** [comment]
New version pushed with **write(n)**,

**Comment by RobTillaart** [comment]
Today I will look at the readme.md, and update it where needed.
Think there is enough functionality and code added for the 0.3.0 version

**Comment by RobTillaart** [comment]
@Devilscave 
0.3.0 released so I close this issue.
If you have troubles or ideas, please open a new issue.
Thanks for all your testing, appreciated
