### ISSUE TITLE
Possibility of use for TLC5917?

### ISSUE THREAD

**Issue by Devilscave** [RobTillaart/TLC5947#6]
Hello Rob,
I have to disturb you again, this is less a problem than a request. So everything is fine with the 24 channel functionality for the TLC5947 and I have made very good progress in my effect development with one of your examples. But now another question, is it possible to use your database for the TLC5917 if you reduce the channels in the cpp from 24 to 8? Unfortunately I haven't found anything for this chip yet.

**Comment by RobTillaart** [comment]
Hi
I have to compare datasheets to see if they are similar enough to make s derived class.
Otherwise a separate library would be the way to go.

**Comment by RobTillaart** [comment]
Quick look at the datasheet, 
Think I should go for a separate library, will take several days as I have a few prio projects at hand.

----

2nd look: completely different

**Comment by RobTillaart** [comment]
>  But now another question, is it possible to use your database for the TLC5917 if you reduce the channels in the cpp from 24 to 8?

To answer the question:  it definitely is not possible to patch the TLC5947 library. 

The TLC5917 internal working is completely different so that means:  build a library from scratch.

I have added this action to my backlog which holds about 50 other libraries to be written.

**Comment by Devilscave** [comment]
OK, then I know, too bad it's not easier. I'm still waiting for the chips myself, then I'll try something out.

**Comment by RobTillaart** [comment]
Let me know when you have the chips. 
I might be able to write a basic library. 
Start with a stripped 5947 lib as the communication seems similar. Just minimal single device, switching LEDS on/off.
If that works extend the library with setting the current. The math involved is not difficult (always dangerous to say)
Multi device should not be too hard either.

**Comment by Devilscave** [comment]
I took your lib from TLC5947, renamed it to TLC5917, also renamed all names and changes in it to 5917 and corrected the channels to 8 and also lowered the brightness level to 255. But I have to test it on the hardware first, it will take some time until it is there. But first codes were compilable without any problems.

**Comment by RobTillaart** [comment]
Ok, did you check and compare the datasheets?

**Comment by Devilscave** [comment]
No, not complete yet 🫣

**Comment by RobTillaart** [comment]
@Devilscave
Found some free time, created a repository TLC5917 here - https://github.com/RobTillaart/TLC5917 - build runs.
- No hardware to test
- supports LED ON/OFF and enable/disable
- has a TLC5916 as derived class, which is functional identical for now.
- support for daisy chaining / cascading (see picture from datasheet)

![image](https://github.com/RobTillaart/TLC5947/assets/462844/270e12c4-8da8-4a3f-99c5-6f5c65b3f0c7)

**Comment by RobTillaart** [comment]
Added **setCurrentAdjustMode()**, **setNormalMode()** and **setConfiguration(uint8_t)**
only intended to work for single device for now.
**setConfiguration(uint8_t)** needs a convenience wrapper to make it usable. 
For now this allows testing different gain levels in "raw" mode.

It is not clear (yet) how to set all the config registers of multi devices (in cascading implementation like above) .

**Comment by Devilscave** [comment]
you are crazy...

**Comment by RobTillaart** [comment]
Topic is continued here - https://github.com/RobTillaart/TLC5917/issues/2
